<a href="https://colab.research.google.com/github/ioa2205/gkpbt-css-circle/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [9]:
arr = np.array([1,2,3,4,5])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

```
# This is formatted as code
```



In [12]:
arr = np.zeros(9)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [14]:
arr = np.array([1,2,3,4,5])
size = np.size(arr)
size

5

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [16]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [19]:
arr = np.zeros(12)
arr[6] = 1
arr

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [20]:
arr = np.arange(20,60)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [23]:
arr = np.arange(1,14)
arr = arr[::-1]
arr

array([13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [25]:
arr = np.arange(12,21).reshape(3,3)
arr

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [26]:
arr = np.array([3,7,0,0,9,0])
arr1 = np.nonzero(arr)
arr1

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [28]:
arr = np.random.random(size = (2,2,2))
arr

array([[[0.57487092, 0.06496172],
        [0.89542205, 0.09425204]],

       [[0.57123987, 0.99013725],
        [0.79543785, 0.10734927]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [30]:
arr = np.random.random(size = (9,9))
print(np.min(arr), np.max(arr))

0.005013396388009794 0.9738299905774582


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [31]:
np.nan, False, False, np.nan, True, True

(nan, False, False, nan, True, True)

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [35]:
arr1 = np.arange(1,19).reshape(6,3)
arr2 = np.arange(1,13).reshape(3,4)
arr = np.dot(arr1, arr2)
arr

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272],
       [218, 260, 302, 344],
       [263, 314, 365, 416]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [36]:
9
10

10

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [37]:
a = np.array([1,2])
b = np.array([4,5])
print(a > b)
print(a >= b)
print(a < b)
print(b <= b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [43]:
np.nan, 0, [-9.22337204e+18]

(nan, 0, [-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [44]:
arr1 = np.array([1,2,3,4,4,5,2,7,8,9])
arr2 = np.array([2,34,4,4,4,5,2,0,1])
arr = np.intersect1d(arr1, arr2)
arr

array([1, 2, 4, 5])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [10]:
arr = np.random.randn(19)*10
arr1 = arr[arr > 0] // 1
arr2 = np.floor(arr[arr > 0])
arr3 = arr[arr > 0].astype(int)
arr4 = np.trunc(arr[arr > 0])
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[ 0. 10.  7. 12.  9.  8.  9.  6.]
[ 0. 10.  7. 12.  9.  8.  9.  6.]
[ 0 10  7 12  9  8  9  6]
[ 0. 10.  7. 12.  9.  8.  9.  6.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [16]:
arr = np.tile(np.arange(3), (3, 1))
arr

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [23]:
arr = np.random.random(size = (1,10))
arr1 = np.sort(arr)
arr1

array([[0.1013008 , 0.15354033, 0.21026936, 0.31690347, 0.51317589,
        0.53092663, 0.55625663, 0.69244872, 0.73380493, 0.76353458]])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [28]:
arr = np.random.random()
arr1 = np.random.random()
print(np.allclose(arr, arr1))
print(np.array_equal(arr,arr1))


False
False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [31]:
arr1 = np.arange(1,19).reshape(6,3)
arr2 = np.arange(7,19).reshape(3,4)
arr = np.dot(arr1, arr2)
arr

array([[ 74,  80,  86,  92],
       [173, 188, 203, 218],
       [272, 296, 320, 344],
       [371, 404, 437, 470],
       [470, 512, 554, 596],
       [569, 620, 671, 722]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [56]:
arr = np.random.rand(5)
arr1 = np.argmax(arr)
arr[arr1] = 0
arr

array([0.29409587, 0.95000623, 0.31631773, 0.        , 0.20957845])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [67]:
date1 = np.datetime64('today', 'D')
date2 = date1 - np.timedelta64(1, 'D')
date3 = date1 + np.timedelta64(1, 'D')
print("Today is ", date1)
print("Yesterday was ", date2)
print("Tomorrow will be ", date3)

Today is  2024-10-13
Yesterday was  2024-10-12
Tomorrow will be  2024-10-14


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [79]:
date = np.arange('2016-01', '2016-02', dtype = 'datetime64[D]')
date

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [86]:
arr = np.random.rand(5)*10
arr
print(arr[arr > 0]//1)
print(np.floor(arr[arr > 0]))
print(arr[arr > 0].astype(int))
print(np.trunc(arr[arr > 0]))

[2. 9. 5. 6. 7.]
[2. 9. 5. 6. 7.]
[2 9 5 6 7]
[2. 9. 5. 6. 7.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [97]:
import time
arr1 = np.arange(11,20).reshape(3,3)
arr2 = np.arange(21,30).reshape(3,3)
arr3 = np.arange(31,40).reshape(3,3)
starttime = time.time()
arr = np.add.reduce(arr1) + np.add.reduce(arr2) + np.add.reduce(arr3)
endtime = time.time()
print(endtime-starttime, "time spent on np.add.reduce")
starttime = time.time()
arr = np.sum(arr1) + np.sum(arr2) + np.sum(arr3)
endtime = time.time()
print(endtime - starttime, "time spent on np.sum")

0.00021839141845703125 time spent on np.add.reduce
0.0003590583801269531 time spent on np.sum


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [101]:
arr = np.array([1,2,3,4,5])
zeros = np.zeros(len(arr)*4-3, dtype=int)
zeros[::4] = arr
zeros

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [109]:
from numpy.lib import stride_tricks
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
stride = a.strides[0]
b = stride_tricks.as_strided(a, shape=(len(a)-3, 4), strides = (stride, stride))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [126]:
arr1 = np.random.rand(10)*10
arr1 = np.floor(arr1).astype(int)
arr1 = np.append(arr1, np.arange(2, 7))
print(arr1)
count = np.bincount(arr1)
most_common = np.argmax(count)
print(most_common, "This is the most common value in the array")


[0 1 6 6 6 0 4 8 8 7 2 3 4 5 6]
6 This is the most common value in the array


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`